name: ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - ubuntu-22.04
          - ubuntu-24.04
    runs-on: ${{ matrix.target }}

    steps:
    - uses: actions/checkout@v3

    - name: update build
      run: |
        sudo apt -qqq -y update
        sudo apt -y dist-upgrade

    - name: install devscripts
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt -qq -y install devscripts equivs lintian
        mk-build-deps -i -s sudo -t "apt --yes --no-install-recommends"

    - name: build source package
      env:
        DEBFULLNAME: "Jakob Flierl"
        DEBEMAIL: "jakob.flierl@gmail.com"
      run: |
        export TARGET=$(. /etc/lsb-release && echo $DISTRIB_CODENAME)
        git fetch --unshallow
        git fetch --tags
        VERSION="1-$(git describe --always --tags | sed -e "s/^v//" -e "s/-/+git/")"
        dch --create \
            --distribution ${TARGET} \
            --package rm501 \
            --newversion ${VERSION}~${TARGET}1 \
            "Automatic build from Github"
        debuild -S -sa -us -uc -d
                                                                                
    - name: build binary package
      run: dpkg-buildpackage -b -rfakeroot -us -uc

    - name: install binary package
      run: sudo dpkg -i ../rm501*deb || true

    - name: install binary package dependencies
      run: sudo apt -f install

    - name: run lintian
      run: lintian ../rm501*deb | lintian-info

    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        if-no-files-found: error
        path: |
          *.buildinfo
          *.changes
          *.dsc
          *.tar.*
          *.deb
          ~/**/*/*.buildinfo
          ~/**/*/*.changes
          ~/**/*/*.dsc
          ~/**/*/*.tar.*
          ~/**/*/*.deb
