name: windows

env:
  CMAKE_BUILD_TYPE: Release
  CMAKE_GENERATOR: Ninja

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  windows:
    runs-on: windows-latest
    name: CMake build on Windows
    timeout-minutes: 15

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        install: >-
          git
          base-devel
          cmake
          ninja
          gcc
          make
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-cc
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_image
          mingw-w64-x86_64-SDL2_ttf
          mingw-w64-x86_64-SDL2_freeglut

    - uses: actions/checkout@v2
      name: Checkout source code

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: CMake configure
      run: cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -G "MinGW Makefiles" -B build

    - name: CMake build
      run: cmake --build build
