name: windows

env:
  CMAKE_BUILD_TYPE: Release
  CMAKE_GENERATOR: Ninja

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  windows:
    runs-on: windows-latest
    name: CMake build on Windows
    timeout-minutes: 15

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          base-devel
          cmake
          ninja
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_image
          mingw-w64-x86_64-SDL2_ttf

    - uses: actions/checkout@v2
      name: Checkout source code

    - name: CMake configure
      run: cmake -B build

    - name: CMake build
      run: cmake --build build
    